name: 'Gobra'
description: 'Verify your Go project with Gobra'
inputs:
  caching:
    description: 'Enable caching of verification results'
    required: true
    default: '0'
  projectLocation:
    description: 'Location in which the project is located in the workflow context (determined by the checkout action for example)'
    required: false
  srcDirectory:
    description: 'Subirectory in which the files to be verified are located'
    required: true
    default: ""
  packageDirectories:
    description: 'Directories used to lookup packages for go (relative to the project location)'
    required: false
  packages:
    description: 'Names of packages to verify, all packages are verified by default'
    required: false
  excludePackages:
    description: 'Names of packages to not include in the verification(this takes precedence over the `package` argument' 
    required: false
  chop:
    description: 'In how many parts a viper program should be split at maximum'
    default: '1'
  viperBackend:
    description: 'Which viper backend to use'
    required: true
    default: "SILICON"
  javaXss:
    description: 'Java stack size'
    required: true
    default: '128m'
  javaXmx:
    description: 'Java max heap size'
    required: true
    default: '4g'
  globalTimeout:
    description: 'Time till verification times out'
    required: true
    default: '5h'
  packageTimeout:
    description: 'Time till package verification times out'
    required: true
    default: '2h'
  imageName:
    description: 'Which base image should be used'
    required: true
    default: 'ghcr.io/viperproject/gobra'
  imageVersion:
    description: 'Which image version should be used'
    required: true
    default: 'latest'
outputs:
  time:
    description: 'Total verification time in seconds'
runs:
  using: 'docker'
  image: 'Dockerfile'
    
