name: 'Gobra'
description: 'Verify your Go project with s'
inputs:
  caching:
    description: 'Enable caching of verification results'
    required: true
    default: 1
  projectLocation:
    description: 'Subirectory in which the project base is located'
    required: true
    default: ""
  packageLocation:
    description: 'Subdirectory of the project location in which the package base is located'
    required: true
    default: ""
  packages:
    description: 'Names of packages to verify, all packages are verified by default'
    required: false
  viperBackend:
    description: 'Which viper backend to use'
    required: true
    defaukt: "SILICON"
  javaXss:
    description: 'Java stack size'
    required: true
    default: '128m'
  javaXmx:
    description: 'Java max heap size'
    required: true
    default: '256m'
  globalTimeout:
    description: 'Time till verification times out'
    required: true
    default: '3h'
  packageTimeout:
    description: 'Time till package verification times out'
    required: true
    default: '1h'
  imageName:
    description: 'Which base image should be used'
    required: true
    default: 'ghcr.io/viperproject/gobra'
  imageVersion:
    description: 'Which image'
    required: true
    default: 'latest'
outputs:
  time: # id of output
    description: 'Total verification time in seconds'
  numberOfPackages:
    description: 'Number of packages verified'
  numberOfFailedPackages:
    description: 'Number of packages, where the verification failed'
  numberOfTimedoutPackages:
    description: 'Number of packages, where the verification timed out'  
  numberOfMethods:
    description: 'Number of methods verified'
  numberOfAssumptions:
    description: 'Number of assumptions'
  numberOfDependingMethods:
    description: 'Number of methods depending on assumptions'
runs:
  using: 'docker'
  image: 'Dockerfile'
    
